### ISSUE TITLE
Why not using custom DSL

### ISSUE THREAD

**Issue by majkinetor** [Slluxx/ImPS#1]
Since you are doing this, why not DSL ?

As an exmaple: 

```
window  {
   title "My awesome UI"
   label "This is almost like ImGui" 20 20
   panel {
       label "Yet another label"
       button "OK" $onOkButton
  }
}

function onOkButton ($window) {
    "OK pressed on " + $window.title
}
```

**Comment by Slluxx** [comment]
ImPS is enspired by Dear ImGui and i want it to behave just like that. It is easy, fast and one doesnt need to learn any kind of structure of how things work to use it. Given my statement about the similarities in the readme, i dont know why i should use DSL.

**Comment by majkinetor** [comment]
It was just a suggestion. Current way is not in the spirit of pwsh.

**Comment by Slluxx** [comment]
I am doing powershell since about a week (general fullstack coding for way longer) and due to your comment, i just looked deeper into DSL. Its an interesting solution although not best practice and definitely not "in the spirit of pwsh". Well, maybe its considered as that now but it definitely wasnt back in the day. 

However, again, an interesting solution. There are some problems with it though which require some thinking-ahead to minimize any kind of drawback this might have over MC. I will try to come up with a prototype and maybe, if it proves to be superior, use that instead.

I should have been more open to a "new" concept in the first place, although i stand by my answer that i wanted something that feels like using ImGui.

**Comment by majkinetor** [comment]
Some well known modules work with DSL, for example [pester](https://pester.dev/), [invoke-build](https://github.com/nightroman/Invoke-Build), [pshtml](https://pshtml.readthedocs.io/en/latest/) etc.

The DSL is superior for writing GUI's IMO as it is less repetitive, structured in the way you think about GUIs, and you don't mess with the C# syntax. You can still offer the same syntax as before along with it because it  may work better in dynamic scenarios.

**Comment by Slluxx** [comment]
After some messing around, i created a simple script that works like this (the _ because "Label" is already defined)
```powershell
Window_ "mywindow" 300 150 {
    Label_ "My first Label" 20 20
    Label_ "my bold label" 20 40 {
        Set-Attr "Font" "Verdana,8,style=Bold"
    }
}
```

However the more i work with it, the less i like this due to multiple reasons. For example:

Set-Attr needs to have access to the created label which, without passing it via pipe or argument, has to check blindly if a variable (`$Element` in this case) exists based on the parent scope.
```powershell
function Set-Attr {
    param ( $Attrib, $Value )
    if (Get-Member -inputobject $Element -name $Attrib -Membertype Properties) {
        $Element.$Attrib = $Value
    } else {
        Write-Host "Attribute $Attrib not found in $($Element)"
    }
}
```

An element might or might not have a clickhandler or other optional arguments and might or might not have its attributes changed in the scriptblock.

```powershell
Window_ "mywindow" 300 150 {
    Label_ "My first Label" 20 20
    Label_ "my bold label" 20 40 {
        Set-Attr "Font" "Verdana,8,style=Bold"
    }
    Button_ "Btn1" 0 0
    Button_ "Btn2" 0 0 $clickhandler
    Button_ "Btn3" 0 0 {
        Set-Attr "Font" "Verdana,8,style=Bold"
    }
    Button_ "Btn4" 0 0  $clickhandler {
        Set-Attr "Font" "Verdana,8,style=Bold"
    }
}
```
Accounting for all of this (optional + moving args) doesnt seem like something that should be done. At most, i could define a `set-clickHandler` function but then we have the same issue as before, where i am relying on the parent scope for variables.

Then again, i could Pipe them - which works but looks horrible or i pass the parent as variable, which  sucks too.

**Comment by majkinetor** [comment]
> Set-Attr needs to have access to the created label which

That is internal detail that can be accomplished. You might also want to expose $_ to the user to refer to the "current parent", although that would work just for first level parents (but easily achievable for higher hierarchy with or without explicit support of the module).

Also some DSL changes could accomplish that:

instead of
```
 Label_ "my bold label" 20 40 {
        Set-Attr "Font" "Verdana,8,style=Bold"
    }
```

you could
```
Label_ "my bold label" 20 40 -Font "Verdana,8,style=Bold" {
}

#or 

Label_ "my bold label" 20 40 {
    $_ | Set-Attr "Font" "Verdana,8,style=Bold"
}
```

Not sure what the problem is with the click handler, you could for example set it inline or use shared one:

```
    Button_ "Btn2" 0 0 -Handler { 
          Write-Host $_.title
    }
    Button_ "Btn3" 0 0 -Handler $btnHandler
        $_ | Set-Attr "Font" "Verdana,8,style=Bold"   #or it could work on $_ by default if no InputObject is set
    }
    Button_ "Btn4" 0 0   -Handler $btnHandler
        Set-Attr "Font" "Verdana,8,style=Bold"
    }
    function btnHandler {   Write-Host $_.title clicked }
```
